---
version: '3'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    networks: 
      - docker
    volumes:
      - /data/appdata/plex:/config
      - /data/storage:/data
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: always
    hostname: tower
    environment:
      - PLEX_CLAIM=${PLEXCLAIM}
      - PUID=${PUID}
      - PLEX_UID=${PUID}
      - PGID=${PGID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP=http://192.168.0.50:32400/

  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    networks:
      - docker
    depends_on:
      - plex
    volumes:
      - /data/appdata/tautulli:/config
      - "/data/appdata/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro"
    ports:
      - 8181:8181/tcp
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Dublin

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    networks: 
      - docker
    depends_on:
      - plex
    volumes:
      - /data/appdata/ombi:/config
      - /data/storage/tv:/tv
      - /data/storage/movies:/movies
      - /data/storage/anime:/anime
    ports:
      - 3579:3579
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    networks: 
      - docker
    volumes:
      - /data/appdata/nzbget/config:/config
      - /data/downloads:/downloads
    ports:
      - 6789:6789
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
      - docker
    depends_on:
      - nzbget
    volumes:
      - /data/appdata/sonarr:/config
      - /data/storage/tv:/tv
      - /data/storage/anime:/anime
      - /data/downloads:/downloads
    ports:
      - 8989:8989
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    networks: 
      - docker
    depends_on:
      - nzbget
    volumes:
      - /data/appdata/radarr:/config
      - /data/storage/movies:/movies
      - /data/storage/anime:/anime
      - /data/downloads:/downloads
    ports:
      - 7878:7878
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

###
#Docker Related Stuff
###

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    networks:
      - docker
    volumes:
      - /data/appdata/letsencrypt:/config
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - EMAIL=${EMAIL}
      - URL=${URL}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare

        #cloudflare-ddns:
        #    image: joshuaavalon/cloudflare-ddns
        #    container_name: cloudflare-ddns
        #    networks:
        #      - docker
        #    restart: always
        #    environment:
        #      - ZONE=${URL}
        #      - HOST=${CFHOST}
        #      - API=${CFAPI}
        #      - EMAIL=${EMAIL}

  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    networks:
      - docker
    ports:
      - 8000:8000/tcp
    environment:
      - DELAY=300
      - ROOTURL=/
      - LISTENINGPORT=8000
      - RECORD1=${DDNSRECORD1}
      - RECORD2=${DDNSRECORD2}

  speedtest:
    image: roest/docker-speedtest-analyser
    container_name: speedtest
    networks:
      - docker
    volumes:
      - /data/appdata/speedtest:/var/www/html/data
    restart: always
    ports:
      - 8080:80
    environment:
      - CRONJOB_ITERATION=10


networks:
  docker:
    driver: bridge
