---
version: '3'
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    networks: 
      - docker
    volumes:
      - /data/appdata/plex:/config
      - /data/storage:/data
      - /data/transcode:/transcode
    ports:
      - 32400:32400
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 5353:5353/udp
      - 1900:1900/udp
    restart: always
    hostname: tower
    environment:
      - PUID=${PUID}
      - PLEX_UID=${PUID}
      - PGID=${PGID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP=http://192.168.0.50:32400/
      - VERSION=latest

  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    networks:
      - docker
    depends_on:
      - plex
    volumes:
      - /data/appdata/tautulli:/config
      - "/data/appdata/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro"
    ports:
      - 8181:8181/tcp
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Dublin

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    networks: 
      - docker
    depends_on:
      - plex
    volumes:
      - /data/appdata/ombi:/config
      - /data/storage/tv:/tv
      - /data/storage/movies:/movies
      - /data/storage/anime:/anime
    ports:
      - 3579:3579
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    networks: 
      - docker
    volumes:
      - /data/appdata/nzbget/config:/config
      - /data/downloads:/downloads
    ports:
      - 6789:6789
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
      - docker
    depends_on:
      - nzbget
    volumes:
      - /data/appdata/sonarr:/config
      - /data/storage/tv:/tv
      - /data/storage/anime:/anime
      - /data/downloads:/downloads
    ports:
      - 8989:8989
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    networks: 
      - docker
    depends_on:
      - nzbget
    volumes:
      - /data/appdata/radarr:/config
      - /data/storage/movies:/movies
      - /data/storage/anime:/anime
      - /data/downloads:/downloads
    ports:
      - 7878:7878
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

###
#Docker Related Stuff
###

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    networks:
      - docker
    volumes:
      - /data/appdata/letsencrypt:/config
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - EMAIL=${EMAIL}
      - URL=${URL}
      - SUBDOMAINS=www,sonarr,radarr,nzbget,ombi
      - VALIDATION=http

  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    networks:
      - docker
    volumes:
      - /data/appdata/ddnsupdater/data:/updater/data
    ports:
      - 8000:8000/tcp
    environment:
      - PUID=${PUID}                                                                                            
      - PGID=${PGID} 

  speedtest:
    image: roest/docker-speedtest-analyser
    container_name: speedtest
    networks:
      - docker
    volumes:
      - /data/appdata/speedtest:/var/www/html/data
    restart: always
    ports:
      - 8080:80
    environment:
      - CRONJOB_ITERATION=10

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --schedule "0 0 4 * * *"

networks:
  docker:
    driver: bridge
